spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/agendaHospitalaria
spring.datasource.username=${DB_USER_POSTGRES}
spring.datasource.password=${DB_PASSWORD_POSTGRES}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

